### ISSUE TITLE
V5 - Only 1 Attribute

### ISSUE THREAD

**Issue by j6s33m** [finity69x2/nws_alerts#85] opened 2024-08-05 12:59 UTC
Is there a reason why in v5, you removed all the individual attributes and lumped all the content into a single attribute? I read and understand that you called out breaking changes in your update notes, but what I fail to understand is how this is better? Do you have new automation examples or dashboard examples of how this is easier/better to use?  At first glance, this feels like a significant downgrade in experience. 

Please help me understand how I should look at this differently. 

Thanks

**Comment by j6s33m** [comment] 2024-08-05 20:10
Those will not as there is only one attribute now with all the data in it. So no way to trigger based on all the prior attributes. 

I downgraded for now, but am still curious as to why the change was made. Hoping we get a better explanation.

**Comment by ruchoff** [comment] 2024-08-06 03:42
You can still pull the different elements of the attribute by indexing into the attribute:

`{{ state_attr('sensor.nws_alerts', 'Alerts')[0]['Event'] }}`

The above is taking the first alert in the Alerts list, `[0]`, then indexing for the value of the key `Event` for that first alert. I was able to update all my cards with this syntax and have had no issues.

**Comment by T3chArmy** [comment] 2024-08-06 17:04
@wormuths I made some new automations for V5 check #87 to see if they fit the bill for your use cases.

**Comment by T3chArmy** [comment] 2024-08-06 18:59
@j6s33m @wormuths I made some new automations for V5 check #87 to see if they fit the bill for your use cases.

**Comment by inguy24** [comment] 2024-08-07 04:56
If I am interpreting things correctly, it sounds like the parsing of the data now falls to me in my automations? Is that correct? If so, do you have an example of what the output could look like in V5 so i would know how to construct a query? I was able to piece together what to expect in each of the attributes in your previous version, but now am a bit mystified as to what is actually being delivered through your integration.

**Comment by j6s33m** [comment] 2024-08-07 14:12
> If I am interpreting things correctly, it sounds like the parsing of the data now falls to me in my automations? Is that correct? If so, do you have an example of what the output could look like in V5 so i would know how to construct a query? I was able to piece together what to expect in each of the attributes in your previous version, but now am a bit mystified as to what is actually being delivered through your integration.

@T3chArmy posed above how to write automations and get the information. Took some getting used to, but I appreciate the examples. I'm sure there is a reason why the owner made this move...still not sure, but I can adjust.

**Comment by T3chArmy** [comment] 2024-08-07 15:10
@j6s33m

To me, this new format is much easier to work with. It's a lot easier to get the information out of the integration. 

Instead of having to split everything at - and hope you're getting the right info.

Now you can loop through the JSON object and know you're getting the relevant info.

Basically the only thing that has changed is the order in which you access the data, and you no longer have to manually split every attribute.

There is a bit of a learning curve, but I agree with the changes the dev has made on this integration. Much better handling of information to make it easier to process.

**Comment by inguy24** [comment] 2024-08-08 07:56
> > If I am interpreting things correctly, it sounds like the parsing of the data now falls to me in my automations? Is that correct? If so, do you have an example of what the output could look like in V5 so i would know how to construct a query? I was able to piece together what to expect in each of the attributes in your previous version, but now am a bit mystified as to what is actually being delivered through your integration.
> 
> @T3chArmy posed above how to write automations and get the information. Took some getting used to, but I appreciate the examples. I'm sure there is a reason why the owner made this move...still not sure, but I can adjust.

I disagree with you there. I went through his automations, but I don't like those automations and prefer to keep all of my automations in Node Red. Those automations do not address any of my needs and do not make it clear what the data set looks like that the author's integration is providing. This is just poor programming and poor documentation. 

You are right that it is the author's own right to trash his own work. But in terms of inferring I cannot read, please keep that to yourself.  I guess it is time for a fork. HACS is pretty strict in terms of things being documented correctly. As the author has not replied as to even providing information on what a dataset looks like that comes from his work, and considering his work is based upon TIMELY and CORRECT alerts to weather phenomena that could be a threat to life and property, I would expect more from the author in terms of their responsibility to the data. and his/her users.

**Comment by rct** [comment] 2024-08-08 16:48
First, this new release was pretty clearly labeled as a breaking change with a new major release number. 

Second, I suggest trying to understand the NWS Alerts API and the various edge conditions. It doesn't seem to be well documented to me. It is an evolution of a very old text based service that was designed in the days of the teletype. 

Third, Home Assistant has been going through its own breaking changes with regards to weather forecasts, textual data, the use (and over use?) of attributes with an eye towards improving efficiency and performance. 

I feel taking it upon yourself to request that someone else's work be removed from HACS is quite offensive. Particularly so because this is a _custom integration_ that someone decided to write and make available _without any compensation_.

**Comment by T3chArmy** [comment] 2024-08-08 22:13
@wormuths I would be happy to lend a hand with updating your automations. Looks like the changes on most of these should be pretty straight forward. 

For most of yours you could simply replace your instances of

`state_attr('sensor.nws_alerts', 'title').split('-')[0]` with `(state_attr(sensor.nws_alerts', 'Alerts') | map(attribute='Headline'))[0]`

There are likely other ways to accomplish this same thing with less code, but that's what immediately comes to mind.

**Comment by T3chArmy** [comment] 2024-08-08 22:38
@wormuths my evening is pretty busy tonight and tomorrow,but I should have time Saturday to take a deep dive into your automation if someone doesn't beat me to it.

In the mean time I'd keep running v4.4 until then.

**Comment by finity69x2** [comment] 2024-08-11 04:42
there are some pretty harsh comments here. especially the one who actually requested my work be removed from HACS. That's pretty crappy so @inguy24 won't be getting any direct help from me on anything further.

For the others, I usually don't interact with users in the issues section here and I prefer to use the HA Forum for this type of thing so if any of you would like to start a thread there I would be more than happy to help you there. Just tag me in the thread. Or even better is just add to the existing thread dedicated to the integration found at https://community.home-assistant.io/t/severe-weather-alerts-from-the-us-national-weather-service/71853

To answer some of the questions...

I hate breaking changes. I really really do. But the way the old integration attributes were laid out was horrendous. the new layout is completely inline with pretty much every single entity that has lists of attributes. The old way was very cumbersome to template and was pretty much completely non-readable for a person. So after a long deliberation I decided to update the integration. 

@j6s33m You are not correct that all the data is in one attribute. There is one "Alert" attribute that contains a list of all the current alerts. Each of those alerts contain exactly the same data that the old integration gave you.

The layout is:

```
Alerts:
  - alert 1 
  - alert 2
  - etc
```

So example to see the event for the first alert in the list the way the data is accessed is 

```
{{state_attr('sensor.nws_alerts', 'Alerts')[0].Event}}
```

to find the description for the third alert:

```
{{state_attr('sensor.nws_alerts', 'Alerts')[2].Description}}
```

all of that is the standard way to template any dictionary of attributes anywhere in HA. And you will notice there are no more cumbersome "splits", "/n", etc anymore.

Then, before releasing the update, I spent several weeks developing example automations and dashboard code to almost replicate the old functionality using the new attribute layout. I think that any changes that are there only make the automations more reliable. I know that not all users are coders and that's why I provide you with a pretty much turn-key package to use out of the box. I can't be held completely responsible for how every individual user ever uses the integration but I try my best to help as much as I can.

Did any of you who are complaining that the old automations won't actually read the readme where I stated that the package and dashboard code examples had been updated to work with the new layout? Did you actually then look at the example code contained there?

Again any of you that would like more in-depth help can start a thread on the HA forum.

But particularly @wormuths...

let's deal with the easiest first - your dashboard card. I'm pretty sure that card is taken directly from my old dashboard example. The updated dashboard example is in the "dashboard" folder in the repo. just replace everything you have now with that code and it should just work. And the improvement is that the old card was limited to just the first 5 alerts. the new card will show all alerts no matter how many there are.

as to you other automations those are a bit more complex to convert but there are many examples given in the package folder as well.

here is the first:

```
alias: Household - Climate (Severe Weather Mode) Tornado Warning - Activate
description: ""
trigger:
  - platform: state
    entity_id: sensor.nws_alerts
condition:
  - condition: template
    value_template: >
      {% set ns = namespace(events=[]) %}
      {% for x in range(0,states('sensor.nws_alerts_test')|int ) %}
        {% set event = state_attr('sensor.nws_alerts_test', 'Alerts')[x].Event %}
        {% set ns.events = ns.events + [event] %}
     {% endfor -%}
     {{ 'Tornado Warning' in ns.events  }}
action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.severe_weather
    alias: Activate Severe Weather Mode
  - alias: Activate Severe Weather Mode (Tornado Warning)
    service: input_boolean.turn_on
    data: {}
    target:
      entity_id:
        - input_boolean.severe_weather_tornado_warning
  - alias: Notify Living Room (LG WebOS Television)
    service: notify.lg_television_wifi_living_room
    data:
      message: The National Weather Service has issued/updated a Tornado Warning.
mode: single
```

it looks at the state of the sensor (and yes the state still gives the count of alerts just like the old version. the only thing changed in the new version is the way the attributes are laid out.) and then checks if any of the alerts are a tornado warning. if yes then the actions are run.

then the second:

```
alias: Household - Climate (Severe Weather Mode) Tornado Warning - Deactivate
description: ""
trigger:
  - platform: state
    entity_id: sensor.nws_alerts
condition:
  - condition: template
    value_template: >
      {% set ns = namespace(events=[]) %}
      {% for x in range(0,states('sensor.nws_alerts_test')|int ) %}
        {% set event = state_attr('sensor.nws_alerts_test', 'Alerts')[x].Event %}
        {% set ns.events = ns.events + [event] %}
     {% endfor -%}
     {{ 'Tornado Warning' not in ns.events  }}
action:
  - alias: Deactivate Severe Weather Mode (Tornado Warning)
    service: input_boolean.turn_off
    data: {}
    target:
      entity_id:
        - input_boolean.severe_weather_tornado_warning
mode: single
```

Again it looks at the state of the sensor and then checks that none of the alerts are a tornado warning. if not then the actions are run.

I haven't fully 100% tested them but in my limited tests (I don't have a tornado warning right now thankfully) I'm fairly confident they will work.

If there is some question then please post in the HA forum for further help.

and to @T3chArmy and @rct thank you for your support.

**Comment by j6s33m** [comment] 2024-08-11 05:58
> there are some pretty harsh comments here. especially the one who actually requested my work be removed from HACS. That's pretty crappy so @inguy24 won't be getting any direct help from me on anything further.
> 
> 
> 
> For the others, I usually don't interact with users in the issues section here and I prefer to use the HA Forum for this type of thing so if any of you would like to start a thread there I would be more than happy to help you there. Just tag me in the thread. Or even better is just add to the existing thread dedicated to the integration found at https://community.home-assistant.io/t/severe-weather-alerts-from-the-us-national-weather-service/71853
> 
> 
> 
> To answer some of the questions...
> 
> 
> 
> I hate breaking changes. I really really do. But the way the old integration attributes were laid out was horrendous. the new layout is completely inline with pretty much every single entity that has lists of attributes. The old way was very cumbersome to template and was pretty much completely non-readable for a person. So after a long deliberation I decided to update the integration. 
> 
> 
> 
> @j6s33m You are not correct that all the data is in one attribute. There is one "Alert" attribute that contains a list of all the current alerts. Each of those alerts contain exactly the same data that the old integration gave you.
> 
> 
> 
> The layout is:
> 
> 
> 
> ```
> 
> Alerts:
> 
>   - dictionary of alert 1 data
> 
>   - dictionary of alert 2 data
> 
>   - etc
> 
> ```
> 
> 
> 
> So example to see the event for the first alert in the list the way the data is accessed is 
> 
> 
> 
> ```
> 
> {{state_attr('sensor.nws_alerts', 'Alerts')[0].Event}}
> 
> ```
> 
> 
> 
> to find the description for the third alert:
> 
> 
> 
> ```
> 
> {{state_attr('sensor.nws_alerts', 'Alerts')[2].Description}}
> 
> ```
> 
> 
> 
> all of that is the standard way to template any dictionary of attributes anywhere in HA. And you will notice there are no more cumbersome "splits", "/n", etc anymore.
> 
> 
> 
> Then, before releasing the update, I spent several weeks developing example automations and dashboard code to almost replicate the old functionality using the new attribute layout. I think that any changes that are there only make the automations more reliable. I know that not all users are coders and that's why I provide you with a pretty much turn-key package to use out of the box. I can't be held completely responsible for how every individual user ever uses the integration but I try my best to help as much as I can.
> 
> 
> 
> Did any of you who are complaining that the old automations won't work anymore actually read the readme where I stated that the package and dashboard code examples had been updated to work with the new layout? Did you actually then look at the example code contained there?
> 
> 
> 
> Again any of you that would like more in-depth help can start a thread on the HA forum.
> 
> 
> 
> But particularly @wormuths...
> 
> 
> 
> let's deal with the easiest first - your dashboard card. I'm pretty sure that card is taken directly from my old dashboard example. The updated dashboard example is in the "dashboard" folder in the repo. just replace everything you have now with that code and it should just work. And the improvement is that the old card was limited to just the first 5 alerts. the new card will show all alerts no matter how many there are.
> 
> 
> 
> as to you other automations those are a bit more complex to convert but there are many examples given in the package folder as well.
> 
> 
> 
> here is the first:
> 
> 
> 
> ```
> 
> alias: Household - Climate (Severe Weather Mode) Tornado Warning - Activate
> 
> description: ""
> 
> trigger:
> 
>   - platform: state
> 
>     entity_id: sensor.nws_alerts
> 
> condition:
> 
>   - condition: template
> 
>     value_template: >
> 
>       {% set ns = namespace(events=[]) %}
> 
>       {% for x in range(0,states('sensor.nws_alerts_test')|int ) %}
> 
>         {% set event = state_attr('sensor.nws_alerts_test', 'Alerts')[x].Event %}
> 
>         {% set ns.events = ns.events + [event] %}
> 
>      {% endfor -%}
> 
>      {{ 'Tornado Warning' in ns.events  }}
> 
> action:
> 
>   - service: input_boolean.turn_on
> 
>     data: {}
> 
>     target:
> 
>       entity_id: input_boolean.severe_weather
> 
>     alias: Activate Severe Weather Mode
> 
>   - alias: Activate Severe Weather Mode (Tornado Warning)
> 
>     service: input_boolean.turn_on
> 
>     data: {}
> 
>     target:
> 
>       entity_id:
> 
>         - input_boolean.severe_weather_tornado_warning
> 
>   - alias: Notify Living Room (LG WebOS Television)
> 
>     service: notify.lg_television_wifi_living_room
> 
>     data:
> 
>       message: The National Weather Service has issued/updated a Tornado Warning.
> 
> mode: single
> 
> ```
> 
> 
> 
> it looks at the state of the sensor (and yes the state still gives the count of alerts just like the old version. the only thing changed in the new version is the way the attributes are laid out.) and then checks if any of the alerts are a tornado warning. if yes then the actions are run.
> 
> 
> 
> then the second:
> 
> 
> 
> ```
> 
> alias: Household - Climate (Severe Weather Mode) Tornado Warning - Deactivate
> 
> description: ""
> 
> trigger:
> 
>   - platform: state
> 
>     entity_id: sensor.nws_alerts
> 
> condition:
> 
>   - condition: template
> 
>     value_template: >
> 
>       {% set ns = namespace(events=[]) %}
> 
>       {% for x in range(0,states('sensor.nws_alerts_test')|int ) %}
> 
>         {% set event = state_attr('sensor.nws_alerts_test', 'Alerts')[x].Event %}
> 
>         {% set ns.events = ns.events + [event] %}
> 
>      {% endfor -%}
> 
>      {{ 'Tornado Warning' not in ns.events  }}
> 
> action:
> 
>   - alias: Deactivate Severe Weather Mode (Tornado Warning)
> 
>     service: input_boolean.turn_off
> 
>     data: {}
> 
>     target:
> 
>       entity_id:
> 
>         - input_boolean.severe_weather_tornado_warning
> 
> mode: single
> 
> ```
> 
> 
> 
> Again it looks at the state of the sensor and then checks that none of the alerts are a tornado warning. if not then the actions are run.
> 
> 
> 
> I haven't fully 100% tested them but in my limited tests (I don't have a tornado warning right now thankfully) I'm fairly confident they will work.
> 
> 
> 
> If there is some question then please post in the HA forum for further help.
> 
> 
> 
> and to @T3chArmy and @rct thank you for your support.
> 
> 

Thanks for the detailed response. I've learned from some of the other ppl over the past few days why this is better and how to properly rewrite automations and scripts to support this new method. While I understand your frustrations with some of the feedback, I do think that your breaking change message didn't properly communicate how to adjust. It was more of a "I made a huge change and  upgrade at your own peril" type of message. Again, I truly am thankful for the work you've done and continue to do. I don't mean any disrespect...was just looking for answers of how to adapt. Really thankful for some of the other posters...gave me a couple examples and I went to the races. 

Again thank you for the work on this integration. It's of huge value to so many.

**Comment by finity69x2** [comment] 2024-08-11 12:52
> I do think that your breaking change message didn't properly communicate how to adjust.

I'm sorry if that's the way it came across.

I honestly thought that this line (even including the misspelling :) ) from the readme would have been sufficient to let people know that there were updated examples in at least the packages folder:

"I have done extensive testing to ensure that the new updated package examplews work as desired"

I'm open to feedback on how it could have been better phrased.

**Comment by jeffxt** [comment] 2024-08-11 13:08
I also support @finity69x2 here.  If you look at the HA forum thread, it answers the two main questions I had, which were:  can I see some examples of real NWS alerts using the new attribute format? (The answer is yes, it does adhere to the structure posted above from the dev themself.)  And is the latest NWS alert going to be at the top, i.e., in reverse chronological order?  (The answer is also yes.)

https://community.home-assistant.io/t/severe-weather-alerts-from-the-us-national-weather-service/71853/545

Since you asked for feedback, @finity69x2, one thing that might have helped was to post a direct link in your release notes when you indicated a breaking change.  Whether that was in your GitHub or directing people to the HA forums post above, I personally think that would have helped reduce some of the questions up front.

That being said, I can tell they are communicating and definitely put in the hard work to maintain this app.  In fact, if there is a donation link, I'd be happy to contribute as a token of my appreciation.  Thanks again for supporting this app, you have no idea how valuable this app is to me and my family!

**Comment by finity69x2** [comment] 2024-08-11 16:29
> one thing that might have helped was to post a direct link in your release notes when you indicated a breaking change.

Point taken.

I'll fix the readme but there's not a lot I can do about the release notes at this point.

Sorry for the confusion.

I'm not a real dev and in my head describing things the way I did I thought it made complete sense.

**Comment by jeffxt** [comment] 2024-08-11 16:57
> > one thing that might have helped was to post a direct link in your release notes when you indicated a breaking change.
> 
> Point taken.
> 
> I'll fix the readme but there's not a lot I can do about the release notes at this point.
> 
> Sorry for the confusion.
> 
> I'm not a real dev and in my head describing things the way I did I thought it made complete sense.

@finity69x2 It's ok!  We're all just learning and tbh, if you didn't tell me that I would not have been able to tell or not :P

I'm a product manager in my day job and one of the things I'm responsible for is putting out release notes for my team.  One thing I always tell my engineers is:  always assume your audience knows nothing.  To be clear -- it's not to be offensive, but it's a good exercise to put your mindset into your users / audience who have zero knowledge of the changes you made, and while that's hard, because devs put in a lot of time and hard work to make changes to their apps, it will help make your release notes clearer and therefore reduce the amount of questions you'll get later down the road (which should also help you)!

Hopefully this is not coming off as giving unsolicited advice, but this was one of the best advice I got from my mentors when I was getting into the world of software development!

**Comment by finity69x2** [comment] 2024-08-12 02:58
I'm closing this as I feel the issue has been adequately addressed.

**Closed by finity69x2** 2024-08-12 02:58 UTC

**Comment by inguy24** [comment] 2024-08-12 04:03
Glad I am not going to get anymore of your help as I never got any in the first place. I asked a simple question... provide documentation of your outputs so we can figure out how to parse the data. You not only didn't do that, you became belligerent. Failure to document is a violation of the HACS agreement. I only filed for a takedown after you failed to provide a very simple answer... and one that should be expected of any developer providing data to an end user.

 IF don't like the heat get out of the kitchen. Creating an integration you use yourself or share with friends is one thing... but listing it on HACS comes with responsibilities. If you do not agree to these responsibilities, which you haven't thus far, then remove the app.









Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
